import Head from "next/head";
import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import "antd/dist/antd.css";
import { Menu, Layout, Button, Breadcrumb } from "antd";
import Image from "next/image";
import logo from "../../public/logo.png";
import {
  MenuUnfoldOutlined,
  MenuFoldOutlined,
  UserOutlined,
  MailOutlined,
  BellOutlined,
} from "@ant-design/icons";
import axios from "axios";

const { Header, Sider, Content } = Layout;
const { SubMenu } = Menu;

export default function ManagerLayout({ children }: any) {
  const router = useRouter();
  const onLogout = () => {
    const userToken = JSON.parse(localStorage.getItem("cms") as string).token;
    console.log(userToken);
    axios
      .post(
        "http://cms.chtoma.com/api/logout",
        {},
        { headers: { Authorization: `Bearer ${userToken}` } }
      )
      .then(() => {
        localStorage.removeItem("cms");
        router.push("/sign-in");
      })
      .catch(function (error) {
        console.log(error);
      });
  };

  const [collapsed, setCollapsed] = useState(false);
  const toggle = () => {
    setCollapsed(!collapsed);
  };

  // useRouter中包含 pathname, query等
  // 小结：使用router获取当前页路径 （React中使用的是withRouter）
  const path = router.pathname;
  console.log("当前路径", router);

  return (
    <div>
      <Head>
        <title>YumEdu Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Sider
          trigger={null}
          collapsible
          collapsed={collapsed}
          width={222}
          defaultCollapsed={true}
          collapsedWidth={100}
        >
          <Menu
            theme="dark"
            mode="inline"
            selectedKeys={[path]}
            inlineCollapsed={collapsed}
            style={{ position: "sticky", top: "0" }}
          >
            <div
              style={{
                height: "80px",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Link href="/" passHref>
                <span style={{ cursor: "pointer" }}>
                  <Image src={logo} alt="logo" width="70" height="70" />
                </span>
              </Link>
            </div>

            <Menu.Item key="/dashboard/manager" icon={<UserOutlined />}>
              <Link href="/dashboard/manager">
                <a>Overview</a>
              </Link>
            </Menu.Item>

            <SubMenu key="sub1" icon={<MailOutlined />} title="Student">
              <Menu.Item key="/dashboard/manager/students">
                <Link href="/dashboard/manager/students">
                  <a>Student List</a>
                </Link>
              </Menu.Item>
            </SubMenu>

            <SubMenu key="sub2" icon={<MailOutlined />} title="Teacher">
              <Menu.Item key="/dashboard/manager/teacher">
                <Link href="/dashboard/manager/teacher">Teacher List</Link>
              </Menu.Item>
            </SubMenu>

            <SubMenu key="sub3" icon={<MailOutlined />} title="Course">
              <Menu.Item key="/dashboard/manager/courses">
                <Link href="/dashboard/manager/courses">All Courses</Link>
              </Menu.Item>
              <Menu.Item key="/dashboard/manager/courses/add-course">
                <Link href="/dashboard/manager/courses/add-course">
                  Add Course
                </Link>
              </Menu.Item>
              <Menu.Item key="/dashboard/manager/courses/edit-course">
                <Link href="/dashboard/manager/courses/edit-course">
                  Edit Course
                </Link>
              </Menu.Item>
            </SubMenu>

            <Menu.Item key="/dashboard/manager/message" icon={<UserOutlined />}>
              <Link href="/dashboard/manager/message">Message</Link>
            </Menu.Item>
          </Menu>
        </Sider>

        <Layout className="site-layout">
          <Header
            className="site-layout-background"
            style={{
              padding: "0 50px",
              height: "80px",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              position: "sticky",
              top: "0",
              zIndex: "9",
            }}
          >
            {React.createElement(
              collapsed ? MenuUnfoldOutlined : MenuFoldOutlined,
              {
                className: "trigger",
                style: { fontSize: "30px", color: "white" },
                onClick: toggle,
              }
            )}

            <div style={{ display: "flex", alignItems: "center" }}>
              <BellOutlined
                style={{
                  color: "white",
                  fontSize: "20px",
                  display: "flex",
                  justifyContent: "flex-end",
                  margin: "0 30px",
                }}
              />

              <Button
                onClick={onLogout}
                icon={<UserOutlined />}
                shape="circle"
              ></Button>
            </div>
          </Header>

          <Content
            className="site-layout-background "
            style={{
              margin: "24px 16px",
              padding: 24,
              minHeight: "calc(100vh - 128px) ",
              backgroundColor: "white",
            }}
          >
            <Breadcrumb>
              <Breadcrumb.Item>CSM MANAGER SYSTEM</Breadcrumb.Item>
              <Breadcrumb.Item>
                <a href="">Application Center</a>
              </Breadcrumb.Item>
              <Breadcrumb.Item>
                <a href="">Application List</a>
              </Breadcrumb.Item>
              <Breadcrumb.Item>An Application</Breadcrumb.Item>
            </Breadcrumb>
            {children}
          </Content>
        </Layout>
      </Layout>
    </div>
  );
}
