import Head from "next/head";
import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import "antd/dist/antd.css";
import { Layout, Button, Breadcrumb, Menu } from "antd";
import Image from "next/image";
import logo from "../../public/logo.png";
import {
  MenuUnfoldOutlined,
  MenuFoldOutlined,
  UserOutlined,
  MailOutlined,
  BellOutlined,
} from "@ant-design/icons";
import { reqSignOut } from "../../service";
import { removeUser } from "../../utils/storageUtils";
import { postLogout, postStudents } from "../../service/api-service";

const { Header, Sider, Content } = Layout;
const { SubMenu } = Menu;

interface LayoutProps {
  children: React.ReactNode;
}

export default function ManagerLayout({ children }: LayoutProps) {
  const router = useRouter();
  const [collapsed, setCollapsed] = useState(false);
  const toggle = () => setCollapsed(!collapsed);
  const pathname = router.pathname;
  const pathsplit: string[] = pathname.split("/");
  const paths = pathsplit.pop();
  const routes = routesMaker(pathsplit);

  // Logout
  const onLogout = () => {
    postLogout().then(() => {
      removeUser();
      router.push("/login");
    });
  };

  function routesMaker(pathsplit: string[]) {
    let routes = [
      {
        path: "index",
        breadcrumbName: "overview",
      },
    ];
    for (let v of pathsplit) {
      const pathInfo = {
        path: v,
        breadcrumbName: v,
      };
      if (v !== "") routes.push(pathInfo);
    }
    return routes;
  }

  return (
    <div>
      <Head>
        <title>YumEdu Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Sider
          trigger={null}
          collapsible
          collapsed={collapsed}
          width={222}
          defaultCollapsed={true}
          collapsedWidth={100}
        >
          <Menu
            theme="dark"
            mode="inline"
            defaultSelectedKeys={["manager"]}
            selectedKeys={[paths as string]}
            defaultOpenKeys={[pathsplit[3]]}
            inlineCollapsed={collapsed}
            style={{ position: "sticky", top: "0" }}
          >
            <div
              style={{
                height: "80px",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Link href="/" passHref>
                <span style={{ cursor: "pointer" }}>
                  <Image src={logo} alt="logo" width="70" height="70" />
                </span>
              </Link>
            </div>

            <Menu.Item key="manager" icon={<UserOutlined />}>
              <Link href="/dashboard/manager" passHref>
                <a>Overview</a>
              </Link>
            </Menu.Item>

            <SubMenu key="students" icon={<MailOutlined />} title="Student">
              <Menu.Item key="student-list">
                <Link href="/dashboard/manager/students/student-list" passHref>
                  <a>Student List</a>
                </Link>
              </Menu.Item>
            </SubMenu>

            <SubMenu key="teacher" icon={<MailOutlined />} title="Teacher">
              <Menu.Item key="teacher-list">
                <Link href="/dashboard/manager/teacher/teacher-list">
                  Teacher List
                </Link>
              </Menu.Item>
            </SubMenu>

            <SubMenu key="courses" icon={<MailOutlined />} title="Course">
              <Menu.Item key="all-courses">
                <Link href="/dashboard/manager/courses/all-courses">
                  All Courses
                </Link>
              </Menu.Item>
              <Menu.Item key="add-course">
                <Link href="/dashboard/manager/courses/add-course">
                  Add Course
                </Link>
              </Menu.Item>
              <Menu.Item key="edit-course">
                <Link href="/dashboard/manager/courses/edit-course">
                  Edit Course
                </Link>
              </Menu.Item>
            </SubMenu>

            <Menu.Item key="message" icon={<UserOutlined />}>
              <Link href="/dashboard/manager/message">Message</Link>
            </Menu.Item>
          </Menu>
        </Sider>

        <Layout className="site-layout">
          <Header
            className="site-layout-background"
            style={{
              padding: "0 50px",
              height: "80px",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              position: "sticky",
              top: "0",
              zIndex: "9",
            }}
          >
            {React.createElement(
              collapsed ? MenuUnfoldOutlined : MenuFoldOutlined,
              {
                className: "trigger",
                style: { fontSize: "30px", color: "white" },
                onClick: toggle,
              }
            )}

            <div style={{ display: "flex", alignItems: "center" }}>
              <BellOutlined
                style={{
                  color: "white",
                  fontSize: "20px",
                  display: "flex",
                  justifyContent: "flex-end",
                  margin: "0 30px",
                }}
              />

              <Button
                onClick={onLogout}
                icon={<UserOutlined />}
                shape="circle"
              ></Button>
            </div>
          </Header>

          <Content
            className="site-layout-background "
            style={{
              margin: "24px 16px",
              padding: 24,
              minHeight: "calc(100vh - 128px) ",
              backgroundColor: "white",
            }}
          >
            <Breadcrumb routes={routes} />

            {children}
          </Content>
        </Layout>
      </Layout>
    </div>
  );
}
