import Head from "next/head";
import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import "antd/dist/antd.css";
import { Layout, Button, Breadcrumb, Menu } from "antd";
import Image from "next/image";
import logo from "../../public/logo.png";
import {
  MenuUnfoldOutlined,
  MenuFoldOutlined,
  UserOutlined,
  BellOutlined,
} from "@ant-design/icons";
import { removeUser } from "../../lib/utils/storageUtils";
import { postLogout } from  "../../pages/api/api-service";
import { generateKey } from '../../lib/utils/side-nav';
import { routes, SideNav } from '../../lib/routes';

const { Header, Sider, Content } = Layout;

interface LayoutProps {
  children: React.ReactNode;
}



function renderMenuItems(data: SideNav[], parent = ''){
  return data.map((item, index) => {
    const key = generateKey(item, index);
    // 判断是否有subNav
    if (item.subNav && !!item.subNav.length) {
      return (
        <Menu.SubMenu key={key} title={item.label} icon={item.icon}>
          {renderMenuItems(item.subNav, item.path.join('/'))} 
        </Menu.SubMenu>
      );
    } else {
      return item.hide ? null : (
        <Menu.Item key={key} title={item.label} icon={item.icon}>
          
          {!!item.path.length || item.label.toLocaleLowerCase() === 'overview' ? (
            <Link
              href={['/dashboard', 'manager', parent, ...item.path]
                .filter((item) => !!item) // 过滤空值
                .join('/')}
              replace // 跳转路由将不会在history中push一个浏览记录，而是取代上一个浏览记录
            >
              {item.label}
            </Link>
          ) : (
            item.label 
          )}
        </Menu.Item>
      );
    }
  });
}


export default function ManagerLayout({ children }: LayoutProps) {
  const router = useRouter();
  const [collapsed, setCollapsed] = useState(false);
  const toggle = () => setCollapsed(!collapsed);
  const sideNav = routes.get('manager')
  const menuItems = renderMenuItems(sideNav);

  // Logout
  const onLogout = () => {
    postLogout().then(() => {
      removeUser();
      router.push("/login");
    });
  };


  return (
    <div>
      <Head>
        <title>YumEdu Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Sider
          trigger={null}
          collapsible
          collapsed={collapsed}
          width={222}
          defaultCollapsed={true}
          collapsedWidth={100}
        >
          <Menu
            theme="dark"
            mode="inline"
            
            inlineCollapsed={collapsed}
            style={{ position: "sticky", top: "0" }}

          >
            <div
              style={{
                height: "80px",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Link href="/" passHref>
                <span style={{ cursor: "pointer" }}>
                  <Image src={logo} alt="logo" width="70" height="70" />
                </span>
              </Link>
            </div>

            {menuItems}

          </Menu>
        </Sider>

        <Layout className="site-layout">
          <Header
            className="site-layout-background"
            style={{
              padding: "0 50px",
              height: "80px",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              position: "sticky",
              top: "0",
              zIndex: "9",
            }}
          >
            {React.createElement(
              collapsed ? MenuUnfoldOutlined : MenuFoldOutlined,
              {
                className: "trigger",
                style: { fontSize: "30px", color: "white" },
                onClick: toggle,
              }
            )}

            <div style={{ display: "flex", alignItems: "center" }}>
              <BellOutlined
                style={{
                  color: "white",
                  fontSize: "20px",
                  display: "flex",
                  justifyContent: "flex-end",
                  margin: "0 30px",
                }}
              />

              <Button
                onClick={onLogout}
                icon={<UserOutlined />}
                shape="circle"
              ></Button>
            </div>
          </Header>

          <Content
            className="site-layout-background "
            style={{
              margin: "24px 16px",
              padding: 24,
              minHeight: "calc(100vh - 128px) ",
              backgroundColor: "white",
            }}
          >
            {/* <Breadcrumb routes={routes} /> */}

            {children}
          </Content>
        </Layout>
      </Layout>
    </div>
  );
}
